---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: forms
  label: Forms
  create: all
  match: "**/*"
- type: directory
  path: ''
  label: Etc
  create: all
  match: "{/*.md,/*.html,/impressum/**/*,/clients/**/*,/about/**/*}"
  exclude: "{/webform.html}"
- type: directory
  path: services
  label: Services
  create: all
  match: "**/*"
  templates:
  - brochure
- type: jekyll-posts
  label: Posts
  create: all
upload_dir: forestry
public_path: http://www.tilix.uk.s3.amazonaws.com/forestry
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
instant_preview: true
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6-node10
  mount_path: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
  preview_command: bundle exec jekyll build --drafts --unpublished --future -d _site
